name: Pull Request Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22.1"
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.55.2

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: weasyprint
        run: |
          sudo apt-get install python3-pip python3-cffi python3-brotli libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0
          pip install weasyprint
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.1"
      - name: Go Mod
        run: go mod download
      - name: Go Mod Verify
        run: go mod verify
      - name: Run Tests
        run: make test
      - name: Go Build
        run: go build -o /dev/null ./...
